{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import os\n",
    "\n",
    "parent_dir = os.path.abspath(os.path.join(os.getcwd(), \"..\"))\n",
    "sys.path.append(parent_dir)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/asyncio/base_events.py\", line 641, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/asyncio/base_events.py\", line 1986, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_46301/3029471730.py\", line 3, in <module>\n",
      "    from helpers import *\n",
      "  File \"/home/elantonino/Big data project/thermal_optimal_path/notebooks/helpers.py\", line 2, in <module>\n",
      "    import pandas as pd\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/__init__.py\", line 49, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/core/api.py\", line 28, in <module>\n",
      "    from pandas.core.arrays import Categorical\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/core/arrays/__init__.py\", line 1, in <module>\n",
      "    from pandas.core.arrays.arrow import ArrowExtensionArray\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/core/arrays/arrow/__init__.py\", line 5, in <module>\n",
      "    from pandas.core.arrays.arrow.array import ArrowExtensionArray\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/core/arrays/arrow/array.py\", line 50, in <module>\n",
      "    from pandas.core import (\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/core/ops/__init__.py\", line 8, in <module>\n",
      "    from pandas.core.ops.array_ops import (\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/core/ops/array_ops.py\", line 56, in <module>\n",
      "    from pandas.core.computation import expressions\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/core/computation/expressions.py\", line 21, in <module>\n",
      "    from pandas.core.computation.check import NUMEXPR_INSTALLED\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/core/computation/check.py\", line 5, in <module>\n",
      "    ne = import_optional_dependency(\"numexpr\", errors=\"warn\")\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/compat/_optional.py\", line 135, in import_optional_dependency\n",
      "    module = importlib.import_module(name)\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/importlib/__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/numexpr/__init__.py\", line 24, in <module>\n",
      "    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/asyncio/base_events.py\", line 641, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/asyncio/base_events.py\", line 1986, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_46301/3029471730.py\", line 3, in <module>\n",
      "    from helpers import *\n",
      "  File \"/home/elantonino/Big data project/thermal_optimal_path/notebooks/helpers.py\", line 2, in <module>\n",
      "    import pandas as pd\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/__init__.py\", line 49, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/core/api.py\", line 28, in <module>\n",
      "    from pandas.core.arrays import Categorical\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/core/arrays/__init__.py\", line 1, in <module>\n",
      "    from pandas.core.arrays.arrow import ArrowExtensionArray\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/core/arrays/arrow/__init__.py\", line 5, in <module>\n",
      "    from pandas.core.arrays.arrow.array import ArrowExtensionArray\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/core/arrays/arrow/array.py\", line 64, in <module>\n",
      "    from pandas.core.arrays.masked import BaseMaskedArray\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/core/arrays/masked.py\", line 60, in <module>\n",
      "    from pandas.core import (\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/core/nanops.py\", line 52, in <module>\n",
      "    bn = import_optional_dependency(\"bottleneck\", errors=\"warn\")\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/pandas/compat/_optional.py\", line 135, in import_optional_dependency\n",
      "    module = importlib.import_module(name)\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/importlib/__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/home/elantonino/Anaconda3/envs/gt/lib/python3.12/site-packages/bottleneck/__init__.py\", line 7, in <module>\n",
      "    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,\n"
     ]
    },
    {
     "ename": "ImportError",
     "evalue": "\nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.0.2 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\ndowngrade to 'numpy<2' or try to upgrade the affected module.\nWe expect that some modules will need time to support NumPy 2.\n\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "File \u001b[0;32m~/Anaconda3/envs/gt/lib/python3.12/site-packages/numpy/core/_multiarray_umath.py:44\u001b[0m, in \u001b[0;36m__getattr__\u001b[0;34m(attr_name)\u001b[0m\n\u001b[1;32m     39\u001b[0m     \u001b[38;5;66;03m# Also print the message (with traceback).  This is because old versions\u001b[39;00m\n\u001b[1;32m     40\u001b[0m     \u001b[38;5;66;03m# of NumPy unfortunately set up the import to replace (and hide) the\u001b[39;00m\n\u001b[1;32m     41\u001b[0m     \u001b[38;5;66;03m# error.  The traceback shouldn't be needed, but e.g. pytest plugins\u001b[39;00m\n\u001b[1;32m     42\u001b[0m     \u001b[38;5;66;03m# seem to swallow it and we should be failing anyway...\u001b[39;00m\n\u001b[1;32m     43\u001b[0m     sys\u001b[38;5;241m.\u001b[39mstderr\u001b[38;5;241m.\u001b[39mwrite(msg \u001b[38;5;241m+\u001b[39m tb_msg)\n\u001b[0;32m---> 44\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mImportError\u001b[39;00m(msg)\n\u001b[1;32m     46\u001b[0m ret \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mgetattr\u001b[39m(_multiarray_umath, attr_name, \u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[1;32m     47\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m ret \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mImportError\u001b[0m: \nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.0.2 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\ndowngrade to 'numpy<2' or try to upgrade the affected module.\nWe expect that some modules will need time to support NumPy 2.\n\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import calendar\n",
    "from helpers import *\n",
    "from thermal_optimal_path.lattice import partition_function\n",
    "from thermal_optimal_path.statistics import average_path\n",
    "from strategies import basic_strategy\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.stats import norm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "year = 2024\n",
    "month = 7\n",
    "temperature = 0.1\n",
    "minute = 40\n",
    "\n",
    "days_in_month = calendar.monthrange(year, month)[1]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing day: 2024-07-01\n",
      "Total money after strategy: Base amount + 0.0005185709473746192\n",
      "Processing day: 2024-07-02\n",
      "Total money after strategy: Base amount + 0.00029155768874411514\n",
      "Processing day: 2024-07-03\n",
      "Total money after strategy: Base amount + 0.0002613864534108945\n",
      "Processing day: 2024-07-04\n",
      "Total money after strategy: Base amount + -0.0001661169864545231\n",
      "Processing day: 2024-07-05\n",
      "Total money after strategy: Base amount + -0.0006346929539805535\n",
      "Processing day: 2024-07-06\n",
      "Total money after strategy: Base amount + 0.0003920871184581731\n",
      "Processing day: 2024-07-07\n",
      "Total money after strategy: Base amount + 0.0007016783001616567\n",
      "Processing day: 2024-07-08\n",
      "Total money after strategy: Base amount + 0.0031626167793078475\n",
      "Processing day: 2024-07-09\n",
      "Total money after strategy: Base amount + 0.001436797386969113\n",
      "Processing day: 2024-07-10\n",
      "Total money after strategy: Base amount + -0.00025197738479820764\n",
      "Processing day: 2024-07-11\n",
      "Total money after strategy: Base amount + 0.0007337802236032642\n",
      "Processing day: 2024-07-12\n",
      "Total money after strategy: Base amount + -0.00043384054300776853\n",
      "Processing day: 2024-07-13\n",
      "Total money after strategy: Base amount + -0.0007331642192153209\n",
      "Processing day: 2024-07-14\n",
      "Total money after strategy: Base amount + -0.00025938376525858065\n",
      "Processing day: 2024-07-15\n",
      "Total money after strategy: Base amount + 0.0004957386381940765\n",
      "Processing day: 2024-07-16\n",
      "Total money after strategy: Base amount + 0.002037886535996236\n",
      "Processing day: 2024-07-17\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[4], line 35\u001b[0m\n\u001b[1;32m     32\u001b[0m eth \u001b[38;5;241m=\u001b[39m eth_prices_std[i:end_time]\n\u001b[1;32m     34\u001b[0m g \u001b[38;5;241m=\u001b[39m partition_function(btc, eth, temperature)\n\u001b[0;32m---> 35\u001b[0m avg_path \u001b[38;5;241m=\u001b[39m \u001b[43maverage_path\u001b[49m\u001b[43m(\u001b[49m\u001b[43mg\u001b[49m\u001b[43m)\u001b[49m[::\u001b[38;5;241m2\u001b[39m]\n\u001b[1;32m     36\u001b[0m weighted_avg \u001b[38;5;241m=\u001b[39m np\u001b[38;5;241m.\u001b[39mdot(avg_path, weights)\n\u001b[1;32m     37\u001b[0m df_avg\u001b[38;5;241m.\u001b[39mappend(weighted_avg)\n",
      "File \u001b[0;32m~/Anaconda3/envs/gt/lib/python3.12/site-packages/numba/core/serialize.py:30\u001b[0m, in \u001b[0;36m_numba_unpickle\u001b[0;34m(address, bytedata, hashed)\u001b[0m\n\u001b[1;32m     26\u001b[0m \u001b[38;5;66;03m# Keep unpickled object via `numba_unpickle` alive.\u001b[39;00m\n\u001b[1;32m     27\u001b[0m _unpickled_memo \u001b[38;5;241m=\u001b[39m {}\n\u001b[0;32m---> 30\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_numba_unpickle\u001b[39m(address, bytedata, hashed):\n\u001b[1;32m     31\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Used by `numba_unpickle` from _helperlib.c\u001b[39;00m\n\u001b[1;32m     32\u001b[0m \n\u001b[1;32m     33\u001b[0m \u001b[38;5;124;03m    Parameters\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     42\u001b[0m \u001b[38;5;124;03m        unpickled object\u001b[39;00m\n\u001b[1;32m     43\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[1;32m     44\u001b[0m     key \u001b[38;5;241m=\u001b[39m (address, hashed)\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "daily_results = {}\n",
    "\n",
    "for day in range(1, days_in_month + 1):\n",
    "    day_str = f\"{day:02d}\"  \n",
    "    print(f\"Processing day: {year}-{month:02d}-{day_str}\")\n",
    "    \n",
    "    btc_path = f'/home/elantonino/Big data project/btc_parquet_data/{year}/{month:02d}/BTCUSDT-1s-{year}-{month:02d}-{day_str}.parquet'\n",
    "    eth_path = f'/home/elantonino/Big data project/eth_parquet_data/{year}/{month:02d}/ETHUSDT-1s-{year}-{month:02d}-{day_str}.parquet'\n",
    "\n",
    "    try:\n",
    "        btc_data = load_parquet(btc_path)\n",
    "        eth_data = load_parquet(eth_path)\n",
    "    except FileNotFoundError:\n",
    "        print(f\"Data for {year}-{month:02d}-{day_str} not found, skipping...\")\n",
    "        continue\n",
    "\n",
    "    btc_prices = btc_data['Open']\n",
    "    eth_prices = eth_data['Open']\n",
    "    btc_prices_std = standardize(btc_prices)\n",
    "    eth_prices_std = standardize(eth_prices)\n",
    "\n",
    "    btc_returns = btc_prices.pct_change().rolling(window=5).mean()[minute:]\n",
    "    eth_returns = eth_prices.pct_change().rolling(window=5).mean()[minute:]\n",
    "\n",
    "    df_avg = []\n",
    "    weights = np.exp(np.linspace(0, 2, minute))  \n",
    "    weights /= weights.sum()\n",
    "    total = len(btc_prices_std)\n",
    "    for i in range(total - minute):\n",
    "        end_time = i + minute\n",
    "        btc = btc_prices_std[i:end_time]\n",
    "        eth = eth_prices_std[i:end_time]\n",
    "\n",
    "        g = partition_function(btc, eth, temperature)\n",
    "        avg_path = average_path(g)[::2]\n",
    "        weighted_avg = np.dot(avg_path, weights)\n",
    "        df_avg.append(weighted_avg)\n",
    "\n",
    "    strategy_result = basic_strategy(\n",
    "        btc_prices[minute:], \n",
    "        btc_returns, \n",
    "        eth_prices[minute:], \n",
    "        eth_returns, \n",
    "        df_avg\n",
    "    )\n",
    "\n",
    "    daily_results[day_str] = {\n",
    "        \"df_avg\": df_avg,\n",
    "        \"btc_returns\": btc_returns,\n",
    "        \"eth_returns\": eth_returns,\n",
    "        \"strategy_result\": strategy_result\n",
    "    }\n",
    "\n",
    "print(\"Finished processing all days.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "gt",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
